-- =========================================================
-- Foreign Key Constraints
-- =========================================================
 
ALTER TABLE HotelPhoneNumbers ADD FOREIGN KEY (HotelID) REFERENCES Hotels (ID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE HotelFeatures ADD FOREIGN KEY (HotelID) REFERENCES Hotels (ID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE Guest ADD FOREIGN KEY (DiscountID) REFERENCES CategoryDiscount (DiscountID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE Occupant ADD FOREIGN KEY (GuestID) REFERENCES Guest (GID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE RoomType ADD FOREIGN KEY (HotelID) REFERENCES Hotels (ID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE RoomTypeFeatures ADD FOREIGN KEY (RoomTypeID) REFERENCES RoomType (RoomTypeID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE Room ADD FOREIGN KEY (HotelID) REFERENCES Hotels (ID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE Room ADD FOREIGN KEY (RoomTypeID) REFERENCES RoomType (RoomTypeID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE Season ADD FOREIGN KEY (HotelID) REFERENCES Hotels (ID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE RoomCost ADD FOREIGN KEY (RoomTypeID) REFERENCES RoomType (RoomTypeID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE RoomCost ADD FOREIGN KEY (HotelID, SeasonName) REFERENCES Season (HotelID, Name) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE Reservation ADD FOREIGN KEY (HotelID) REFERENCES Hotels (ID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE Reservation ADD FOREIGN KEY (GuestID) REFERENCES Guest (GID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE Stay ADD FOREIGN KEY (ReservationID) REFERENCES Reservation (ReservationID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE Stay ADD FOREIGN KEY (GuestID) REFERENCES Guest (GID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE Billing ADD FOREIGN KEY (reservation_id) REFERENCES Reservation (ReservationID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE Billing ADD FOREIGN KEY (guest_id) REFERENCES Guest (GID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE Billing ADD FOREIGN KEY (hotel_id) REFERENCES Hotels (ID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE ReservationRoom ADD FOREIGN KEY (ReservationID) REFERENCES Reservation (ReservationID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE ReservationRoom ADD FOREIGN KEY (HotelID, RoomNumber) REFERENCES Room (HotelID, RoomNumber) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE StayRoom ADD FOREIGN KEY (StayID) REFERENCES Stay (ID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE StayRoom ADD FOREIGN KEY (HotelID, RoomNumber) REFERENCES Room (HotelID, RoomNumber) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE StayRoomService ADD FOREIGN KEY (StayID) REFERENCES Stay (ID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE StayRoomService ADD FOREIGN KEY (RoomServiceID) REFERENCES RoomService (RoomServiceID) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE BillingDiscount ADD FOREIGN KEY (bill_id) REFERENCES Billing (bill_id) DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE BillingDiscount ADD FOREIGN KEY (DiscountID) REFERENCES CategoryDiscount (DiscountID) DEFERRABLE INITIALLY IMMEDIATE;